### ISSUE TITLE
Crashes if gnome-settings-daemon is not running

### ISSUE THREAD

**Issue by DarwinAwardWinner** [Kilian/f.lux-indicator-applet#3]
If gnome-settings-daemon is not running, fluxgui crashes with the following:

```
$ fluxgui
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/fluxgui/fluxgui.py", line 365, in <module>
    app = Fluxgui()
  File "/usr/lib/pymodules/python2.6/fluxgui/fluxgui.py", line 17, in __init__
    self.indicator = Indicator(self)
  File "/usr/lib/pymodules/python2.6/fluxgui/fluxgui.py", line 134, in __init__
    self.setup_indicator()
  File "/usr/lib/pymodules/python2.6/fluxgui/fluxgui.py", line 145, in setup_indicator
    'gtk-icon-theme-name')
ValueError: could not find setting
```

This can be a problem in KDE, which obviously doesn't run gnome-settings-daemon by default.

**Comment by AndrewDCox** [comment]
I was having the same problem and found that the workaround from @sricks did the trick!

I'm on Linux Mint 17 Qiana (Ubuntu 14.04.1) running the KDE desktop

**Comment by zbyna** [comment]
Thanks for nice fix @sricks  :thumbsup:
