### ISSUE TITLE
RuntimeError: called outside of a mainloop

### ISSUE THREAD

**Issue by wrichert** [Kilian/f.lux-indicator-applet#36]
On Ubuntu 13.10 after installing python-gconf and python-appindicator I get:

Critical error. Exiting.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fluxgui/fluxapp.py", line 271, in <module>
    app = FluxGUI()
  File "/usr/local/lib/python2.7/dist-packages/fluxgui/fluxapp.py", line 30, in **init**
    self.exit(1)
  File "/usr/local/lib/python2.7/dist-packages/fluxgui/fluxapp.py", line 49, in exit
    gtk.main_quit()
RuntimeError: called outside of a mainloop

**Comment by RanchoCooper** [comment]
same problem

OS: Arch Linux by `yaourt fluxgui`

**Comment by 3usi9** [comment]
When installing it, before exec setup.py, it's necessary to check a file "xflux"
If it doesn't exist (in most cases, even every dependence met), you should exec  
```bash
    python ./download-xflux.py
```
before install.
