### ISSUE TITLE
ValueError:could not find setting

### ISSUE THREAD

**Issue by fboerman** [Kilian/f.lux-indicator-applet#39]
i get an error when i try to run flux on ubuntu 13.10 with openbox:

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/fluxgui/fluxgui.py", line 381, in <module>
    app = Fluxgui()
  File "/usr/lib/pymodules/python2.7/fluxgui/fluxgui.py", line 17, in **init**
    self.indicator = Indicator(self)
  File "/usr/lib/pymodules/python2.7/fluxgui/fluxgui.py", line 149, in **init**
    self.setup_indicator()
  File "/usr/lib/pymodules/python2.7/fluxgui/fluxgui.py", line 162, in setup_indicator
    'gtk-icon-theme-name')
ValueError: could not find setting

**Comment by mardukbp** [comment]
Same here with awesome WM.

**Comment by fjagugar** [comment]
I've bypassed the error commenting out lines from 160 to 166 in /usr/lib/pymodules/python2.7/fluxgui/fluxgui.py. (Ubuntu with awesome WM)

In any case, if you are experiencing problems with flux in awesome WM, you may want to try xflux.
