### ISSUE TITLE
Support for Ubuntu 15.04?

### ISSUE THREAD

**Issue by kodeine** [Kilian/f.lux-indicator-applet#55]
I tried to install on 15.04 but it couldnt get it from ppa. Any help would be appreciated.

**Comment by jalcine** [comment]
He'd have to bump Launchpad to generate sources for Vivid. Mind doing so @Kilian? If not, setting up a team on Launchpad could help in letting others help out.

**Comment by Kilian** [comment]
I could but that would be a false promise; The code as it stand doesn't work nicely with 15.04 and would need to be updated or rewritten.

**Comment by jalcine** [comment]
Hmm. There's [a fork](https://github.com/Mystro256/f.lux-indicator-applet) I've been using that works not only on 15.04 but on KDE as well. I've debated rolling that into a PPA, but @Kilian, a _lot_ more people use this and follow your PPA. I wouldn't want to split that away.

**Comment by kodeine** [comment]
@Kilian is right, i installed on my ubuntu 15.04 and my system crashed. blank screen after reboot.

**Comment by jalcine** [comment]
@kodeine Is this something that happens only on 15.04 or did it occur in 14.10 as well?

**Comment by kodeine** [comment]
@jalcine 
only on 15.04. 
14.xx was working fine.

**Comment by jalcine** [comment]
On Friday, June 05, 2015 09:22:45 PM Kodeine wrote:
> @jalcine
> only on 15.04.
> 14.xx was working fine.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Kilian/f.lux-indicator-applet/issues/55#issuecomment-1095
> 19059

Interesting (I asked because I saw an open issue about problems on 14.10).
-- 
Jacky Alcine - https://jacky.wtf/about
-----------------------------
They can read this message, know who you are and where you live.
Encrypt EVERYTHING. NOW. More: https://jacky.wtf/gpg/

**Comment by analytically** [comment]
+1

**Comment by NHellFire** [comment]
[Mystro256/f.lux-indicator-applet](https://github.com/Mystro256/f.lux-indicator-applet) or [my repo](https://github.com/NHellFire/f.lux-indicator-applet) work on Ubuntu 15.04. My guess is the old xflux binary was causing problems.

**Comment by jalcine** [comment]
Awesome. This will help me out a lot.

**Comment by balaclark** [comment]
Is there any that works with 15.10?

**Comment by NHellFire** [comment]
My fork should work, untested though.

**Comment by str** [comment]
@NHellFire do you have a ppa?

**Comment by andypost** [comment]
I'm using old ```deb http://ppa.launchpad.net/kilian/f.lux/ubuntu trusty main``` in 15.10
just replaced binaries from https://justgetflux.com/linux.html ```xflux64.tgz```
it works fine in previous 15.04 as well

**Comment by dvorapa** [comment]
@andypost :+1:

**Comment by ev1l0rd** [comment]
@str @andypost @dvorapa I have a ppa available, I just copied the packages from Kilian's old repository. It works up to wily (although wily is still building).
 
https://launchpad.net/~blackmage/+archive/ubuntu/f.lux

Or if you would rather want the command served to you to do this:
> sudo add-apt-repository ppa:blackmage/f.lux; sudo apt-get update; sudo apt-get install -y fluxgui

**Comment by dvorapa** [comment]
@ev1l0rd Could you add Trusty to your ppa please? 14.04.2 worked like a charm and since 14.04.3 there is the same bug like in Vivid or Willy

**Comment by dvorapa** [comment]
@ev1l0rd :+1:

**Comment by dvorapa** [comment]
@ev1l0rd not working :-1:

**Comment by cjduncana** [comment]
@dvorapa Which PPA do you say does not work? [Kilian](http://ppa.launchpad.net/kilian/f.lux/ubuntu/dists/vivid/main/binary-amd64/Packages) or [Blackmage](https://launchpad.net/~blackmage/+archive/ubuntu/f.lux)? Kilian is still down for me, but Blackmage still works as expected.

**Comment by dvorapa** [comment]
For me both (Kilian and Blackmage) not working (U 15.10 64bit). But @andypost solution works

**Comment by NHellFire** [comment]
I've made a PPA for my packages now: ppa:nathan-renniewaldock/flux

https://launchpad.net/~nathan-renniewaldock/+archive/ubuntu/flux

My package is working on 15.04 and should work on others (I've got builds for 12.04 to 16.04)

**Comment by ntc2** [comment]
@NHellFire: on 15.10, I think your package needs a `python-glade2` dependency. Before installing that, I got
```console
 fluxgui
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/fluxgui/fluxapp.py", line 6, in <module>
    import gtk.glade
ImportError: No module named glade
```

**Comment by ntc2** [comment]
@NHellFire: and on 15.04 I had different problems. First, I was getting
```console
$ fluxgui                                
Traceback (most recent call last):
  File "/usr/bin/fluxgui", line 19, in <module>
    import fluxgui
ImportError: No module named fluxgui
```
Looking in `/usr/share/pyshared/fluxgui`, I saw there was no `__init__.py` file, so I did
```console
$ sudo touch /usr/share/pyshared/fluxgui/__init__.py
$ sudo chmod a+r /usr/share/pyshared/fluxgui/__init__.py
```
and then `fluxgui` worked.

However, looking at my 15.10 machine, I see there is no `__init__.py` file there either, so I don't know why I needed to add one on the 15.04 machine.

**Comment by NHellFire** [comment]
I've uploaded a new package adding python-glade2 as a dependency. As for
__init__.py, it seems it gets left out the binary package because it's empty

**Comment by ntc2** [comment]
Re the `__init__.py`, I see on my 15.04 system that for example the `iotop`
package installed an empty `__init__.py` file. Looking at the contents of
the `iotop` `.deb` package (using `apt-get download iotop; mkdir iotop-dir;
dpkg-deb -R iotop*.deb iotop-dir`), I can't find any special treatment for
the empty file. However, I think you're saying that the file gets left out
of your package during the creation of the `.deb`.

Oh, and it looks like you also added an `__init__.py` to your package this
morning! I did `aptitude update; aptitude purge fluxgui; rm -rf
/usr/share/pyshared/fluxgui; aptitude install fluxgui`, which got me your
new package with your new `__init__.py`. However, I'm still getting
```console
$ fluxgui
Traceback (most recent call last):
  File "/usr/bin/fluxgui", line 19, in <module>
    import fluxgui
ImportError: No module named fluxgui
```
If I `cd` to `/usr/share/pyshared`, or `export
PYTHONPATH=/usr/share/pyshared:$PYTHONPATH` then running `fluxgui` works,
but I have no idea why the `__init__.py` is not sufficient now???

One thing I notice is that all of the other Python packages I have that
installed files in `/usr/share/pyshared` actually load from other
directories:
```console
$ cd ~

$ ls -l /usr/share/pyshared
total 32K
drwxr-xr-x 17 root root 4.0K Jan 15 14:04 ansible/
drwxr-xr-x  2 root root 4.0K Jan 15 14:04 ansible-2.0.0.2.egg-info/
drwxr-xr-x  2 root root 4.0K Feb  1 11:14 fluxgui/
-rw-r--r--  1 root root  566 Feb  1 09:26
f.lux_indicator_applet-1.1.8.egg-info
drwxr-xr-x  2 root root 4.0K Feb  2  2015 iotop/
-rw-r--r--  1 root root  348 Jun  7  2013 iotop-0.6.egg-info
drwxr-xr-x  2 root root 4.0K Oct 15 12:50 Pyste/
-rw-r--r--  1 root root  324 Mar  7  2015 Pyste-0.9.10-py2.7.egg-info

$ python
Python 2.7.9 (default, Apr  2 2015, 15:33:21)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ansible
>>> ansible.__file__
'/usr/lib/pymodules/python2.7/ansible/__init__.pyc'
>>> import iotop
>>> iotop.__file__
'/usr/lib/python2.7/dist-packages/iotop/__init__.pyc'
>>> import Pyste
>>> Pyste.__file__
'/usr/lib/python2.7/dist-packages/Pyste/__init__.pyc'
>>> import fluxgui
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named fluxgui
```
I don't know anything about Python packaging on Debian, but this could be
relevant.

**Comment by ntc2** [comment]
@NHellFire:

(Sorry about the terrible formatting on the last message, but I can't figure out how to make GitHub not interpret the Python `>>>` prompts as me quoting a previous message.)

I figured out why you adding the `__init__.py` file to your package did not solve the problem for me: before adding a `__init__.py` file myself yesterday, I had first added `/usr/share/pyshared` to my `PYTHONPATH` to the shell is was using to install your package. When that did not fix the problem, I eventually noticed that the `__init__.py` file was missing, but at that point I had forgotten about changing my `PYTHONPATH`. Today, I was using different shell to install the new version of your package, so I no longer had `/usr/share/pyshared` on my `PYTHONPATH`. Sorry about the confusion.

So, the second problem is that `/usr/share/pyshared` isn't on the default Python path:
```console
$ unset PYTHONPATH; python -c 'from __future__ import print_function; import sys; map(lambda p: print(repr(p)), sys.path)' 
''
'/usr/lib/python2.7'
'/usr/lib/python2.7/plat-x86_64-linux-gnu'
'/usr/lib/python2.7/lib-tk'
'/usr/lib/python2.7/lib-old'
'/usr/lib/python2.7/lib-dynload'
'/usr/local/lib/python2.7/dist-packages'
'/usr/lib/python2.7/dist-packages'
'/usr/lib/python2.7/dist-packages/PILcompat'
'/usr/lib/python2.7/dist-packages/gtk-2.0'
'/usr/lib/pymodules/python2.7'
'/usr/lib/python2.7/dist-packages/ubuntu-sso-client'
```
Indeed, as I mentioned in my last message above, all of the other packages I have installed in `/usr/share/pyshared` load from somewhere else, either `/usr/lib/python2.7/dist-packages` or `/usr/lib/pymodules/python2.7`. Looking at the [Debian Python Packaging Policy](https://www.debian.org/doc/packaging-manuals/python-policy/ch-python.html), it seems that `/usr/share/pyshared` may not be supported anymore:
> When binary packages ship identical source code for multiple Python versions, for instance /usr/lib/python2.6/dist-packages/foo.py and /usr/lib/python2.5/site-packages/foo.py, these should point to a common file. Version specific directories for identical source code are not required for python3 and must not be used for this. Since python2.7 is the last python2 version and the only supported version in wheezy and later releases, a common location to share arch-independent files across Python versions is no longer needed. Historically the location for this was /usr/share/pyshared. For python2.7, use of /usr/lib/python2.7/dist-packages is sufficient. For python3, a special location is not required, use /usr/lib/python3/dist-packages

So, I think the solution is to install the `fluxgui` package under `/usr/lib/python2.7/dist-packages`. Looking at packages.ubuntu.com, I see that even the oldest supported version of Ubuntu, 12.04LTS, [has Python 2.7 as the default Python](http://packages.ubuntu.com/precise/python). The `iotop` package installs in `/usr/lib/python2.7/dist-packages` by symlinking from `/usr/share/pyshared`:
```console
$ dpkg -L iotop | grep '\.py' | xargs ls -l
lrwxrwxrwx 1 root root    40 Jun  7  2013 /usr/lib/python2.7/dist-packages/iotop/data.py -> ../../../../share/pyshared/iotop/data.py
lrwxrwxrwx 1 root root    45 Jun  7  2013 /usr/lib/python2.7/dist-packages/iotop/genetlink.py -> ../../../../share/pyshared/iotop/genetlink.py
lrwxrwxrwx 1 root root    44 Jun  7  2013 /usr/lib/python2.7/dist-packages/iotop/__init__.py -> ../../../../share/pyshared/iotop/__init__.py
lrwxrwxrwx 1 root root    42 Jun  7  2013 /usr/lib/python2.7/dist-packages/iotop/ioprio.py -> ../../../../share/pyshared/iotop/ioprio.py
lrwxrwxrwx 1 root root    43 Jun  7  2013 /usr/lib/python2.7/dist-packages/iotop/netlink.py -> ../../../../share/pyshared/iotop/netlink.py
lrwxrwxrwx 1 root root    38 Jun  7  2013 /usr/lib/python2.7/dist-packages/iotop/ui.py -> ../../../../share/pyshared/iotop/ui.py
lrwxrwxrwx 1 root root    43 Jun  7  2013 /usr/lib/python2.7/dist-packages/iotop/version.py -> ../../../../share/pyshared/iotop/version.py
lrwxrwxrwx 1 root root    42 Jun  7  2013 /usr/lib/python2.7/dist-packages/iotop/vmstat.py -> ../../../../share/pyshared/iotop/vmstat.py
-rw-r--r-- 1 root root 14928 May 26  2013 /usr/share/pyshared/iotop/data.py
-rw-r--r-- 1 root root  2044 May 26  2013 /usr/share/pyshared/iotop/genetlink.py
-rw-r--r-- 1 root root     0 May 26  2013 /usr/share/pyshared/iotop/__init__.py
-rw-r--r-- 1 root root  5495 May 26  2013 /usr/share/pyshared/iotop/ioprio.py
-rw-r--r-- 1 root root  7891 May 26  2013 /usr/share/pyshared/iotop/netlink.py
-rw-r--r-- 1 root root 23727 May 26  2013 /usr/share/pyshared/iotop/ui.py
-rw-r--r-- 1 root root    16 May 26  2013 /usr/share/pyshared/iotop/version.py
-rw-r--r-- 1 root root  1559 May 26  2013 /usr/share/pyshared/iotop/vmstat.py
```
but I expect that you can do away with `/usr/share/pyshared` all together and just install into `/usr/lib/python2.7/dist-packages` directly (although I don't have a 12.04 system to test this hypothesis on).

**Comment by NHellFire** [comment]
I'm not specifying an install directory, it uses debhelper (which is the
preferred way) so it goes in the correct directories.
I've figured out the problem anyway, I was missing the debhelper token from
the postinst script, so it wasn't inserting the commands to add it to the
actual module dir. Uploading a new package now to fix that.

**Comment by ntc2** [comment]
@NHellFire: just tried your new package on 15.04 and everything works. :+1:

**Comment by jmgomezpoveda** [comment]
This issue is a duplicate of https://github.com/Kilian/f.lux-indicator-applet/issues/23

**Comment by cm-s** [comment]
@ev1l0rd your ppa worked for me (15.10)
The gui won't show yet though...

**Comment by ntc2** [comment]
@cm-s: I recently ran into a "GUI won't show" bug:
- details: https://github.com/Kilian/f.lux-indicator-applet/issues/66#issuecomment-186770071
- fix: https://github.com/Kilian/f.lux-indicator-applet/pull/71.
Is this what you ran into?

**Comment by drewklassen** [comment]
@NHellFire Many thanks for this.  (Running on 15.10 - MATE)

**Comment by tinof** [comment]
@NHellFire while trying to install from your ppa (Ubuntu 16.04 GNOME), I get this:

The following packages have unmet dependencies:
 fluxgui : Depends: python-support (>= 0.90.0) but it is not installable
E: Unable to correct problems, you have held broken packages.

How could I fix this?

**Comment by drewklassen** [comment]
Would anyone happen to have suggestions for flux pegging my CPU at 100%?   This is not occasionally, the CPU is max'd anytime flux is active.

I am running Ubuntu-MATE 15.10 x64 fully updated.  Cheers

**Comment by NHellFire** [comment]
@tinof Thanks, it looks like python-support was dropped in favour of dh-python since I uploaded that package. I'll upload a new build in a few days to deal with that. If I haven't done it by Friday, could you remind me? I might forget with everything I've got going on next week.

**Comment by dvorapa** [comment]
Yeah, that's the same error I got on my 15.10

**Comment by HustLion** [comment]
@NHellFire thanks. With you ppa I get it  working. For others who might have the same question, the steps needed to get f.lux working is: 

``` bash
sudo add-apt-repository ppa:nathan-renniewaldock/flux
sudo apt-get update
sudo apt-get install fluxgui
```

And then press super key ( I'm using Ubuntu 16.04 LTS) and type flux and you will see `f.lux indicator applet`. Launch it and click on the `Find your latitude and longitude` button, then type back in the data to f.lux. I don't know if f.lux start working once you type the data in, but for me, after typing in the longitude value, in the input box I pressed enter and then f.lux start working.

I think the windows version is much more intuitive than this linux version. Maye later someone could improve the linux version. Anyway, thanks guys this is working now.

And for me there is no python issue. Maybe it's because I've already installed python tools before. So if anyone run into python issues, please refer above.
